// PDF Generator for Onboarding Reports
// Uses pdfkit to create professional PDF documents

import PDFDocument from "pdfkit";
import { OnboardingReport, PDFGenerationOptions, ReportRecommendation } from "@/types/report";
import { getStatusInfo } from "./onboarding-report";

// Brand colors
const COLORS = {
  primary: "#4F46E5", // Indigo
  secondary: "#6366F1",
  success: "#10B981",
  warning: "#F59E0B",
  error: "#EF4444",
  text: "#1F2937",
  textLight: "#6B7280",
  background: "#F9FAFB",
  border: "#E5E7EB",
  white: "#FFFFFF",
};

// Helper to format currency
function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount);
}

// Helper to format date
function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

// Helper to format percentage
function formatPercentage(value: number): string {
  return `${Math.round(value)}%`;
}

// Generate PDF from report
export async function generateOnboardingPDF(
  report: OnboardingReport,
  options: PDFGenerationOptions = {}
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({
        size: "LETTER",
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: `Client Onboarding Report - ${report.clientInfo.businessName}`,
          Author: "OnboardLy",
          Subject: "Client Onboarding Report",
          Creator: "OnboardLy PDF Generator",
        },
      });

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Page 1: Executive Summary
      renderExecutiveSummary(doc, report);

      // Page 2: Document Inventory
      doc.addPage();
      renderDocumentInventory(doc, report);

      // Page 3: Missing Documents
      doc.addPage();
      renderMissingDocuments(doc, report);

      // Page 4: Financial Overview
      if (report.transactionSummary.totalTransactions > 0) {
        doc.addPage();
        renderFinancialOverview(doc, report);
      }

      // Page 5: Chart of Accounts Summary
      doc.addPage();
      renderChartOfAccountsSummary(doc, report);

      // Page 6: Next Steps & Recommendations
      if (options.includeRecommendations !== false) {
        doc.addPage();
        renderNextSteps(doc, report);
      }

      // Add page numbers
      const pageCount = doc.bufferedPageRange().count;
      for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);

        // Footer
        doc.fontSize(8)
          .fillColor(COLORS.textLight)
          .text(
            `Generated by OnboardLy on ${formatDate(report.clientInfo.reportGeneratedAt)}`,
            50,
            doc.page.height - 40,
            { align: "left" }
          )
          .text(
            `Page ${i + 1} of ${pageCount}`,
            50,
            doc.page.height - 40,
            { align: "right", width: doc.page.width - 100 }
          );
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

// Render Executive Summary (Page 1)
function renderExecutiveSummary(doc: PDFKit.PDFDocument, report: OnboardingReport): void {
  const pageWidth = doc.page.width - 100;

  // Header with logo placeholder
  doc.fillColor(COLORS.primary)
    .fontSize(24)
    .text("OnboardLy", 50, 50)
    .fontSize(10)
    .fillColor(COLORS.textLight)
    .text("Client Onboarding Report", 50, 78);

  // Title
  doc.moveDown(2)
    .fillColor(COLORS.text)
    .fontSize(28)
    .text(report.clientInfo.businessName, { align: "center" })
    .fontSize(14)
    .fillColor(COLORS.textLight)
    .text(`Industry: ${report.clientInfo.industry.replace("-", " ")}`, { align: "center" })
    .text(`Project: ${report.clientInfo.projectName}`, { align: "center" });

  // Completeness Score Circle
  const scoreY = 200;
  const scoreX = doc.page.width / 2;

  // Draw circular score indicator
  const score = report.overallCompletenessScore;
  const statusInfo = getStatusInfo(report.status);
  const scoreColor = score >= 80 ? COLORS.success : score >= 50 ? COLORS.warning : COLORS.error;

  doc.save()
    .circle(scoreX, scoreY, 50)
    .lineWidth(8)
    .strokeColor(COLORS.border)
    .stroke()
    .restore();

  doc.save()
    .circle(scoreX, scoreY, 50)
    .lineWidth(8)
    .strokeColor(scoreColor)
    .stroke()
    .restore();

  doc.fillColor(COLORS.text)
    .fontSize(32)
    .text(formatPercentage(score), scoreX - 35, scoreY - 15, { width: 70, align: "center" });

  doc.fontSize(10)
    .fillColor(COLORS.textLight)
    .text("COMPLETENESS", scoreX - 50, scoreY + 20, { width: 100, align: "center" });

  // Status Badge
  doc.moveDown(6)
    .fillColor(scoreColor)
    .fontSize(14)
    .text(statusInfo.label.toUpperCase(), { align: "center" })
    .fontSize(10)
    .fillColor(COLORS.textLight)
    .text(statusInfo.description, { align: "center" });

  // Key Metrics
  doc.moveDown(2);
  const metricsY = doc.y;
  const metricWidth = pageWidth / 3;

  // Documents Received
  doc.fillColor(COLORS.text)
    .fontSize(24)
    .text(String(report.documentCoverage.totalDocuments), 50, metricsY, {
      width: metricWidth,
      align: "center",
    })
    .fontSize(10)
    .fillColor(COLORS.textLight)
    .text("Documents Received", 50, metricsY + 30, { width: metricWidth, align: "center" });

  // Transactions Extracted
  doc.fillColor(COLORS.text)
    .fontSize(24)
    .text(String(report.transactionSummary.totalTransactions), 50 + metricWidth, metricsY, {
      width: metricWidth,
      align: "center",
    })
    .fontSize(10)
    .fillColor(COLORS.textLight)
    .text("Transactions Extracted", 50 + metricWidth, metricsY + 30, {
      width: metricWidth,
      align: "center",
    });

  // Accounts Set Up
  doc.fillColor(COLORS.text)
    .fontSize(24)
    .text(String(report.chartOfAccounts.totalAccounts), 50 + metricWidth * 2, metricsY, {
      width: metricWidth,
      align: "center",
    })
    .fontSize(10)
    .fillColor(COLORS.textLight)
    .text("Accounts Set Up", 50 + metricWidth * 2, metricsY + 30, {
      width: metricWidth,
      align: "center",
    });

  // Top Action Items
  const highPriorityRecs = report.recommendations.filter((r) => r.priority === "high").slice(0, 3);
  if (highPriorityRecs.length > 0) {
    doc.moveDown(4)
      .fillColor(COLORS.text)
      .fontSize(14)
      .text("Top Action Items", { underline: true })
      .moveDown(0.5);

    for (const rec of highPriorityRecs) {
      doc.fillColor(COLORS.error)
        .fontSize(10)
        .text("●", { continued: true })
        .fillColor(COLORS.text)
        .text(`  ${rec.title}`, { continued: false })
        .fontSize(9)
        .fillColor(COLORS.textLight)
        .text(`    ${rec.description}`)
        .moveDown(0.3);
    }
  }
}

// Render Document Inventory (Page 2)
function renderDocumentInventory(doc: PDFKit.PDFDocument, report: OnboardingReport): void {
  const pageWidth = doc.page.width - 100;

  // Header
  renderPageHeader(doc, "Document Inventory");

  doc.moveDown()
    .fontSize(10)
    .fillColor(COLORS.textLight)
    .text("Summary of all documents received, organized by category.");

  // Table header
  doc.moveDown();
  const tableTop = doc.y;
  const colWidths = [200, 60, 150, 100];

  doc.rect(50, tableTop, pageWidth, 25).fill(COLORS.background);
  doc.fillColor(COLORS.text).fontSize(9);
  doc.text("Category", 55, tableTop + 8);
  doc.text("Count", 55 + colWidths[0], tableTop + 8);
  doc.text("Date Range", 55 + colWidths[0] + colWidths[1], tableTop + 8);
  doc.text("Status", 55 + colWidths[0] + colWidths[1] + colWidths[2], tableTop + 8);

  // Table rows
  let y = tableTop + 30;
  const receivedCategories = new Set(report.documentCoverage.documentsReceived.map((d) => d.category));

  const allCategories = [
    { category: "bank_statement", label: "Bank Statements" },
    { category: "credit_card", label: "Credit Card Statements" },
    { category: "payroll", label: "Payroll / Pay Stubs" },
    { category: "invoice", label: "Vendor Invoices" },
    { category: "tax_document", label: "Tax Documents" },
    { category: "receipt", label: "Receipts" },
    { category: "contract", label: "Contracts" },
    { category: "other", label: "Other" },
  ];

  for (const cat of allCategories) {
    const received = report.documentCoverage.documentsReceived.find(
      (d) => d.category === cat.category
    );

    if (y > doc.page.height - 100) {
      doc.addPage();
      y = 50;
    }

    // Alternating row background
    if ((allCategories.indexOf(cat) % 2) === 0) {
      doc.rect(50, y - 5, pageWidth, 22).fill("#FAFAFA");
    }

    doc.fillColor(COLORS.text).fontSize(9);
    doc.text(cat.label, 55, y);
    doc.text(received ? String(received.count) : "0", 55 + colWidths[0], y);

    if (received && received.dateRange) {
      doc.text(
        `${formatDate(received.dateRange.start)} - ${formatDate(received.dateRange.end)}`,
        55 + colWidths[0] + colWidths[1],
        y,
        { width: colWidths[2] - 10 }
      );
    } else {
      doc.fillColor(COLORS.textLight).text("-", 55 + colWidths[0] + colWidths[1], y);
    }

    // Status indicator
    const hasDocuments = receivedCategories.has(cat.category);
    const statusX = 55 + colWidths[0] + colWidths[1] + colWidths[2];
    doc.fillColor(hasDocuments ? COLORS.success : COLORS.error)
      .text(hasDocuments ? "✓ Received" : "✗ Missing", statusX, y);

    y += 25;
  }

  // Summary
  doc.moveDown(2)
    .fillColor(COLORS.text)
    .fontSize(11)
    .text(`Total Documents: ${report.documentCoverage.totalDocuments}`)
    .fontSize(10)
    .fillColor(COLORS.textLight)
    .text(
      `Coverage: ${report.documentCoverage.dateRangeCoverage.monthsCovered} of ${report.documentCoverage.dateRangeCoverage.monthsExpected} months`
    );
}

// Render Missing Documents (Page 3)
function renderMissingDocuments(doc: PDFKit.PDFDocument, report: OnboardingReport): void {
  renderPageHeader(doc, "Missing Documents");

  if (report.documentCoverage.documentsMissing.length === 0) {
    doc.moveDown(2)
      .fillColor(COLORS.success)
      .fontSize(14)
      .text("All expected documents have been received!", { align: "center" })
      .moveDown()
      .fillColor(COLORS.textLight)
      .fontSize(10)
      .text("No critical documents are missing from this client's file.", { align: "center" });
    return;
  }

  doc.moveDown()
    .fontSize(10)
    .fillColor(COLORS.textLight)
    .text("The following documents are expected but have not been received:");

  doc.moveDown();

  for (const missing of report.documentCoverage.documentsMissing) {
    if (doc.y > doc.page.height - 150) {
      doc.addPage();
    }

    // Priority indicator
    const priorityColor =
      missing.priority === "high"
        ? COLORS.error
        : missing.priority === "medium"
          ? COLORS.warning
          : COLORS.textLight;

    doc.fillColor(priorityColor)
      .fontSize(12)
      .text(`● ${missing.label}`, { continued: false })
      .fontSize(10)
      .fillColor(COLORS.text)
      .text(missing.reason)
      .moveDown(0.3);

    if (missing.missingMonths && missing.missingMonths.length > 0) {
      doc.fillColor(COLORS.textLight)
        .fontSize(9)
        .text(`Missing months: ${missing.missingMonths.join(", ")}`, { indent: 15 });
    }

    doc.moveDown();
  }

  // Month coverage gap visualization
  if (report.documentCoverage.dateRangeCoverage.gaps.length > 0) {
    doc.moveDown()
      .fillColor(COLORS.text)
      .fontSize(11)
      .text("Statement Coverage Gaps", { underline: true })
      .moveDown(0.5)
      .fillColor(COLORS.textLight)
      .fontSize(9)
      .text(`The following months are missing bank or credit card statements:`)
      .moveDown(0.3)
      .text(report.documentCoverage.dateRangeCoverage.gaps.join(", "));
  }
}

// Render Financial Overview (Page 4)
function renderFinancialOverview(doc: PDFKit.PDFDocument, report: OnboardingReport): void {
  const pageWidth = doc.page.width - 100;
  const summary = report.transactionSummary;

  renderPageHeader(doc, "Financial Overview");

  // Date range
  if (summary.dateRange) {
    doc.moveDown()
      .fillColor(COLORS.textLight)
      .fontSize(10)
      .text(
        `Transaction Period: ${formatDate(summary.dateRange.start)} to ${formatDate(summary.dateRange.end)}`
      );
  }

  // Key financial metrics
  doc.moveDown();
  const metricsY = doc.y;
  const metricWidth = pageWidth / 2;

  // Income box
  doc.rect(50, metricsY, metricWidth - 10, 70).fill("#ECFDF5");
  doc.fillColor(COLORS.success)
    .fontSize(10)
    .text("TOTAL INCOME", 60, metricsY + 10)
    .fontSize(20)
    .text(formatCurrency(summary.totalIncome), 60, metricsY + 28)
    .fontSize(9)
    .fillColor(COLORS.textLight)
    .text(`${summary.incomeTransactionCount} transactions`, 60, metricsY + 52);

  // Expenses box
  doc.rect(50 + metricWidth, metricsY, metricWidth - 10, 70).fill("#FEF2F2");
  doc.fillColor(COLORS.error)
    .fontSize(10)
    .text("TOTAL EXPENSES", 60 + metricWidth, metricsY + 10)
    .fontSize(20)
    .text(formatCurrency(summary.totalExpenses), 60 + metricWidth, metricsY + 28)
    .fontSize(9)
    .fillColor(COLORS.textLight)
    .text(`${summary.expenseTransactionCount} transactions`, 60 + metricWidth, metricsY + 52);

  // Net amount
  doc.moveDown(5)
    .fillColor(COLORS.text)
    .fontSize(12)
    .text(`Net Amount: ${formatCurrency(summary.netAmount)}`)
    .fontSize(10)
    .fillColor(COLORS.textLight)
    .text(`Average Transaction: ${formatCurrency(summary.averageTransactionSize)}`);

  // Top Vendors
  if (summary.topVendors.length > 0) {
    doc.moveDown(2)
      .fillColor(COLORS.text)
      .fontSize(12)
      .text("Top 10 Vendors by Spend", { underline: true })
      .moveDown(0.5);

    const tableTop = doc.y;
    doc.rect(50, tableTop, pageWidth, 20).fill(COLORS.background);
    doc.fillColor(COLORS.text).fontSize(9);
    doc.text("Vendor", 55, tableTop + 5);
    doc.text("Transactions", 300, tableTop + 5);
    doc.text("Total", 400, tableTop + 5);

    let y = tableTop + 25;
    for (const vendor of summary.topVendors.slice(0, 10)) {
      if (y > doc.page.height - 80) break;

      doc.fillColor(COLORS.text).fontSize(9);
      doc.text(vendor.vendor.substring(0, 40), 55, y, { width: 240 });
      doc.text(String(vendor.transactionCount), 300, y);
      doc.text(formatCurrency(vendor.totalAmount), 400, y);
      y += 18;
    }
  }
}

// Render Chart of Accounts Summary (Page 5)
function renderChartOfAccountsSummary(doc: PDFKit.PDFDocument, report: OnboardingReport): void {
  const pageWidth = doc.page.width - 100;
  const coa = report.chartOfAccounts;

  renderPageHeader(doc, "Chart of Accounts Summary");

  if (coa.totalAccounts === 0) {
    doc.moveDown(2)
      .fillColor(COLORS.warning)
      .fontSize(14)
      .text("No Chart of Accounts Created Yet", { align: "center" })
      .moveDown()
      .fillColor(COLORS.textLight)
      .fontSize(10)
      .text(
        "Generate a chart of accounts to organize transactions and prepare for export.",
        { align: "center" }
      );
    return;
  }

  doc.moveDown()
    .fillColor(COLORS.textLight)
    .fontSize(10)
    .text(`Industry Template: ${coa.industry.replace("-", " ")}`);

  // Accounts by type
  doc.moveDown()
    .fillColor(COLORS.text)
    .fontSize(12)
    .text("Accounts by Type", { underline: true })
    .moveDown(0.5);

  const tableTop = doc.y;
  doc.rect(50, tableTop, pageWidth, 20).fill(COLORS.background);
  doc.fillColor(COLORS.text).fontSize(9);
  doc.text("Account Type", 55, tableTop + 5);
  doc.text("Count", 400, tableTop + 5);

  let y = tableTop + 25;
  for (const typeInfo of coa.accountsByType) {
    doc.fillColor(COLORS.text).fontSize(9);
    doc.text(typeInfo.type, 55, y);
    doc.text(String(typeInfo.count), 400, y);
    y += 18;
  }

  // Total
  doc.rect(50, y, pageWidth, 20).fill(COLORS.background);
  doc.fillColor(COLORS.text).fontSize(9);
  doc.text("Total Accounts", 55, y + 5, { bold: true } as PDFKit.Mixins.TextOptions);
  doc.text(String(coa.totalAccounts), 400, y + 5);

  // Export formats
  doc.moveDown(4)
    .fillColor(COLORS.text)
    .fontSize(12)
    .text("Available Export Formats", { underline: true })
    .moveDown(0.5)
    .fontSize(10)
    .text("• QuickBooks Online (CSV)")
    .text("• QuickBooks Desktop (IIF)")
    .text("• Xero (CSV)");
}

// Render Next Steps (Page 6)
function renderNextSteps(doc: PDFKit.PDFDocument, report: OnboardingReport): void {
  renderPageHeader(doc, "Next Steps & Recommendations");

  // Recommendations
  doc.moveDown()
    .fillColor(COLORS.text)
    .fontSize(12)
    .text("Recommendations", { underline: true })
    .moveDown(0.5);

  if (report.recommendations.length === 0) {
    doc.fillColor(COLORS.success)
      .fontSize(10)
      .text("No outstanding recommendations. This client is ready for export!");
  } else {
    for (const rec of report.recommendations) {
      if (doc.y > doc.page.height - 120) {
        doc.addPage();
      }

      const priorityColor =
        rec.priority === "high"
          ? COLORS.error
          : rec.priority === "medium"
            ? COLORS.warning
            : COLORS.textLight;

      doc.fillColor(priorityColor)
        .fontSize(10)
        .text(`[${rec.priority.toUpperCase()}]`, { continued: true })
        .fillColor(COLORS.text)
        .text(` ${rec.title}`)
        .fontSize(9)
        .fillColor(COLORS.textLight)
        .text(rec.description, { indent: 20 });

      if (rec.actionItem) {
        doc.fillColor(COLORS.primary).text(`→ ${rec.actionItem}`, { indent: 20 });
      }

      doc.moveDown(0.5);
    }
  }

  // Client Checklist
  doc.moveDown()
    .fillColor(COLORS.text)
    .fontSize(12)
    .text("Client Checklist", { underline: true })
    .moveDown(0.5)
    .fontSize(10);

  const clientItems = report.documentCoverage.documentsMissing
    .filter((m) => m.priority === "high" || m.priority === "medium")
    .map((m) => `Provide ${m.label}`);

  if (clientItems.length === 0) {
    doc.fillColor(COLORS.success).text("✓ All required documents received");
  } else {
    for (const item of clientItems.slice(0, 5)) {
      doc.fillColor(COLORS.text).text(`☐ ${item}`);
    }
  }

  // Bookkeeper Checklist
  doc.moveDown()
    .fillColor(COLORS.text)
    .fontSize(12)
    .text("Bookkeeper Checklist", { underline: true })
    .moveDown(0.5)
    .fontSize(10);

  const bookkeepItems: string[] = [];

  if (report.transactionSummary.totalTransactions === 0 && report.documentCoverage.totalDocuments > 0) {
    bookkeepItems.push("Extract transactions from uploaded documents");
  }
  if (report.chartOfAccounts.totalAccounts === 0) {
    bookkeepItems.push("Generate chart of accounts");
  }
  const unmapped = report.transactionSummary.transactionsByAccount.find(
    (a) => a.accountNumber === "unassigned"
  );
  if (unmapped && unmapped.transactionCount > 0) {
    bookkeepItems.push(`Review ${unmapped.transactionCount} unmapped transactions`);
  }
  if (report.status === "ready") {
    bookkeepItems.push("Export to accounting software");
    bookkeepItems.push("Schedule follow-up with client");
  }

  if (bookkeepItems.length === 0) {
    bookkeepItems.push("Review exported data in accounting software");
    bookkeepItems.push("Schedule follow-up with client");
  }

  for (const item of bookkeepItems) {
    doc.fillColor(COLORS.text).text(`☐ ${item}`);
  }
}

// Helper: Render page header
function renderPageHeader(doc: PDFKit.PDFDocument, title: string): void {
  doc.fillColor(COLORS.primary)
    .fontSize(18)
    .text(title, 50, 50);

  doc.moveTo(50, 75)
    .lineTo(doc.page.width - 50, 75)
    .strokeColor(COLORS.border)
    .stroke();

  doc.y = 85;
}
